spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type.descriptor.sql: trace
#        stat: debug
    com.atomikos: debug

datasource:
  first:
    url: jdbc:mysql://localhost:13306/test?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234

  second:
    url: jdbc:mysql://localhost:23306/test?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234

